### ISSUE TITLE
after_transition syntax or bug?

### ISSUE THREAD

**Issue by rosskevin** [state-machines/state_machines#10]
This fired my method:

```
after_transition all => :paid, do: :process_payment
```

This did not:

```
after_transition on: :paid, do: :process_payment
```

Bug or am I misunderstand the `:on` as a shortcut for `all`?

**Comment by james2m** [comment]
@rosskevin yeah, on: is for the name of an event, not a state.

**Comment by rosskevin** [comment]
@james2m @seuros I'm just going to start tracking these questions as I go, hopefully it will help.

https://github.com/state-machines/state_machines/wiki/FAQ-and-Gotchas

**Comment by seuros** [comment]
:+1:  Thank you
