### ISSUE TITLE
Single boolean argument to event method is not passed as transition.args to after_transition method

### ISSUE THREAD

**Issue by rosskevin** [state-machines/state_machines#12]
```ruby
state_machine :state, initial: :uninitialized do
     event :cancel do
        transition [:trial, :active, :grace] => :canceled
      end

      after_transition on: :cancel, do: :process_cancel
end

def process_cancel(transition)
    terminate = transition.args[0] || false
end
```

1. `subscription.cancel!(true)` yields `transition.args` empty
2. `subscription.cancel!(true, 'foo')` yields `transition.args` length 2 `# [true, 'foo']`
3. `subscription.cancel!('foo')` yields `transition.args` length 1 `# ['foo']`

**Comment by rosskevin** [comment]
This indeed seems to be a bug, but I think I'm going to switch to passing an options hash to the event methods, that way it is not order dependent.

**Comment by damncabbage** [comment]
Confirmed; pass it a boolean on the tail end of an arguments list and it gets eaten, eg. `0, 0, false`, `99, "abc", true`, etc.

**Comment by damncabbage** [comment]
I think this is unfortunately a works-as-designed:

From http://www.rubydoc.info/github/pluginaweek/state_machine/master/StateMachine/Machine:event:
> `park(..., run_action = true)` - Fires the “park” event, transitioning from the current state to the next valid state. If the last argument is a boolean, it will control whether the machine's action gets run.

(It's the `.cancel()` itself that's swallowing the boolean.)

**Comment by rosskevin** [comment]
That feels...at least unexpected.  Not hard to workaround, just really unexpected.

**Comment by damncabbage** [comment]
Agreed. I've personally tripped over it at least once myself; it's like you need to put your args in a tuple or nested array to avoid the last-arg tag-check thing.
