### ISSUE TITLE
ActiveRecord

### ISSUE THREAD

**Issue by tquackenbush** [state-machines/state_machines#13]
Is ActiveRecord supported like in the 'state_machine' gem?
State does not seem to be persisted with a database field of 'state'...
Am I missing something?

**Comment by seuros** [comment]
The integrations are in separate gems.
For AR state_machines-activerecord

**Comment by tquackenbush** [comment]
Oh, cool. Thank you!

**Comment by shoresh** [comment]
Yeah but the state_machines_activerecord gem requires Rails 4.  I'm using state machines with Rails 3 in an activerecord model and once a record is saved, rec.state always returns nil.  Is there any way to address this without upgrading to Rails 4?
