### ISSUE TITLE
upgrade path from state_machine?

### ISSUE THREAD

**Issue by jjb** [state-machines/state_machines#14]
Hi,

Thanks for this great project. I didn't know about it until a couple days ago.

I think many of your users will be transitioning here from the state_machine gem. Do you think you could add a couple lines to the readme explaining what the upgrade path is? Is it a seamless transition?

If you answer in this issue then I'll be happy to submit a PR.

Thanks!

**Comment by seuros** [comment]
The module name changed from `StateMachine` to `StateMachines`
And the integrations are in separate gems.
Dropped support for old Rubies/AR/Mongo/ect.

**Comment by seuros** [comment]
And the tests are green :green_heart:

**Comment by agis-** [comment]
Hello @seuros!

Unfortunately, in a Rails 3.2 app (ruby 2.1.5) where I was using `state_machine` (latest version), I switched to `state_machines` (latest version) and I get test failures. Apparently something has changed and state_machines is not 100% backwards-compatible with state_machine.

I'm currently investigating what might be causing these failures but if you had any insight on this, it would be very helpful. Thanks!

**Comment by seuros** [comment]
Do you still use rails 3.2 ?  The integrations are in separate gems.

**Comment by agis-** [comment]
Yes, I'm on 3.2 and in the process of upgrading to 4.x. I've also added the integration gems:

- state_machines-activemodel
- state_machines-activerecord

but the same failures are present even when using these gems.

**Comment by seuros** [comment]
```state_machines-activerecord``` will require all the other gems.  
What type of failure do you have ?
Can you provide a sample apple that replicate the error ?

**Comment by agis-** [comment]
I've removed `state_machine` 1.1.2 and replaced it with `state_machines-activerecord` 0.0.0 (the only version that does not depend on rails 4.x) and I get a new failure: 

```shell
```

**Comment by seuros** [comment]
Ah. I should yank that version, sorry for the confusion.
state_machines-activerecord support from 4.1+.
my fork of the legacy gem support until 4.0.

**Comment by agis-** [comment]
So for Rails 3.2 should we use your fork? ([seuros/state_machine](https://github.com/seuros/state_machine)?

**Comment by seuros** [comment]
You can . But new features are added to this org only.
