### ISSUE TITLE
Refactor: rescue Exception

### ISSUE THREAD

**Issue by rosskevin** [state-machines/state_machines#20]
When I was working on transactions, I saw `rescue Exception` in a lot of places.  As far as I know, we don't have a need for it in state_machines (but I could be wrong).  Perhaps we should consider switching to `rescue => error` or just `rescue`.

References:
- http://stackoverflow.com/a/10048406/2363935
- https://robots.thoughtbot.com/rescue-standarderror-not-exception

**Comment by seuros** [comment]
:+1:  
Probably legacy code.
