### ISSUE TITLE
not sure of an issue... maybe just lake of knownloedge and effective information in my situation.

### ISSUE THREAD

**Issue by jerome2** [state-machines/state_machines#21]
on rails-4.2 with ruby-2.2.2, after installed the_teacher/the_comments, i have problem to submit comment due to server error 500 point on active_machine error.
here is the error:
"NoMethodError (protected method `around_validation' called for #<StateMachine::Machine:0x0000000624a990>):"

then after looking around this to fix, i see a patch find by this one (the_teacher), but would like to upgrade rails to something really works fine without patches things. Then i start to read some posts/issues around this. And try to install this gem.
I'm not sure to real understand what's happen due to big datas posted (i sink under all of these datas). So i don't know how to do to really use one of your fix for fix state_machine (i never find any clear instruction for do that... so i'm not an expert, for sure).
I would be very happy to read a pragmatic instructions article around "how to fix state-machine".
Or if this is an issue, to know how to find a nice solution.
Thanks for all.

**Comment by seuros** [comment]
ping @the-teacher

`the comments` gem depend on the legacy gem, maybe we should upgrade it to use state_machines.

**Comment by jerome2** [comment]
I understand better. But i supposed you could understand  also that this not resolve the problem totaly for the fact that "the legacy state_machine is the problem due to no more been maintained'. And then, this choice could not be mine and i can not have a intelligent opinion about that (this could be pretentious), but @the-teacher one is free to do this choice or not and take the risk to change is code many times because the 'states_machines is not legacy one'. @the-teacher find a patch solution who really is simple and works fine (also this resolve the problem for his own gem and maybe some other). 
So i think everybody could understand that if the code from 'state-machines' is clean and safety (and then i have not the required level to know that), then the best way could be to do state_machines the legacy ones instead of hold the old unmaintained one (and i'm far from the opinions/politics speaks around: "why this choice is not choose ?"). Did you try to contact Rails team to speak with them about this fact ?
If state_machines will become legacy, then officialy peoples hackers who create gems could choose without any futur problems to use them. I think this way is the "cleanest" one.
Then when you talk about "fork mine", you talk to people construct gems file in fa

**Comment by jerome2** [comment]
I understand better. But i supposed you understand also that this not resolve the problem totaly for the fact that "the legacy state_machine is the problem due to no more been maintained'. And then, this choice to use yours instead of the legacy one could not be mine and i can not have a intelligent opinion about that (this could be pretentious), but @the-teacher is free to do this choice and take the risk to change is code many times because the 'states_machines is not legacy one' (and i think this is the real problem: why not do it legacy ? What's happen with Rails team ? What is they own arguments around that ?). @the-teacher find a patch solution who really is simple and works fine (also this resolve the problem for his own gem and maybe some other). 
So i think everybody could understand that if the code from 'state-machines' is clean and safety (and then i have not the required level to know that), then the best way could be to do state_machines the legacy ones instead of hold the old unmaintained one (and i'm far from the opinions/politics speaks around: "why this choice is not choose ?", but i really curious to know the argulments of each concerned hackers around this question). Did you try to contact Rails team to speak with them about this fact ?
If state_machines will become legacy, then officialy peoples hackers who create gems could choose without any futur problems to use them. I think this way is the "cleanest" one.
Then when you talk about "fork mine", you talk to people construct gems file in fact ? (i think i can use it... but don't know how to do it) And the final hackers users... they have to wait for rails decide to use a maintained code for his codes ? What's happen between you and Rails who make this so difficult to just do it ? I think it is this point precisly i not understand.
So for now, i wait a link for be able to understand what's happen, and i use the patch provided by @the-teacher (the easy way)... i hope really to have one day a serious Rails framework to use (i think it is allready nice... but why not use a maintained code for state_machine ? i don't know... i would like to know that).
Thanks for your answer and for link informations around this problem decision Rails team not choose and arguments around that.

**Comment by rosskevin** [comment]
Closing since the issue involves another gem depending on the old state_machine gem (not this gem).
