### ISSUE TITLE
Add `with_state` method

### ISSUE THREAD

**Issue by johannesluedke** [state-machines/state_machines#26]
Migrating from state_machine, I am missing the `.with_state` option. Could it be included to this gem to make it more compatible?

Syntax: 

    Model.with_state([:new, :confirmed]

queries for objects WHERE state IN (?), ["new", "confirmed"]

**Comment by seuros** [comment]
Model ?

You need to use https://github.com/state-machines/state_machines-activerecord

**Comment by johannesluedke** [comment]
Sorry, you are right.
Still, exchanging state_machine with this gem and its active record add on doesn't give me backwards compatibility though :(

**Comment by seuros** [comment]
Let move this discussion to the other repo, please.
We need to write a migration guide if the change is not straightforward.
