### ISSUE TITLE
Can not access the class

### ISSUE THREAD

**Issue by magicalbanana** [state-machines/state_machines#27]
So I am using Virtus with State Machine and it seems with this approach state machine can not access the class.

Any thoughts?

**Comment by rosskevin** [comment]
@magicalbanana can you provide a stack trace?

**Comment by magicalbanana** [comment]
```
      undefined local variable or method `loan_application' for #<StateMachines::Machine:0x007fc28421f3d8> (NameError)
```
That's my error.

**Comment by magicalbanana** [comment]
I believe the issue is state machine is unable to access the methods in the class, perhaps a conflict with Virtus.

**Comment by seuros** [comment]
If you could share a sample app, i would take a look .

**Comment by magicalbanana** [comment]
It actually works.

I just passed in a block instead, which I guess is what the DSL should be anyway.

before
```
after_transition any => any do
  method
end
```

after
```
after_transition any => any do |klass, transition|
  klass.method #works now
end
```
