### ISSUE TITLE
.state returning nil

### ISSUE THREAD

**Issue by balancedcomp** [state-machines/state_machines#28]
I just switched over from pluginaweek's repo, and now all tests fail because state is returning nil. 

```
state_machine :state, initial: :inactive do

    before_transition any => :active, do: :archive_currently_active_adjustment
    after_transition  any => :active, do: :update_employee_current_salary!

    event :activate do
      transition any => :active
    end

    event :archive do
      transition any => :historical
    end

    event :queue do
      transition any => :pending
    end

  end
  
def initialize
    super() # NOTE: This *must* be called, otherwise states won't get initialized
  end
```

Here's a sample from the console:

```
SalaryAdjustment Load (13.1ms)  SELECT  "salary_adjustments".* FROM "salary_adjustments" WHERE "salary_adjustments"."deleted_at" IS NULL  ORDER BY effective_date ASC LIMIT 1
 => #<SalaryAdjustment id: 48750, employee_id: 7304, scenario_id: nil, created_at: "2012-09-17 17:32:40", updated_at: "2012-09-21 15:29:08", memo: "6mo review", effective_date: "12-12-0001", position_title: "Teller", date_in_position: "08-18-2011", status: "inactive", new_wages: #<BigDecimal:7fea35ccbce0,'0.9E1',9(18)>, state: "historical", deleted_at: nil>
```

You can can that state is set to 'historical'. But...

```
2.2.2 :002 > SalaryAdjustment.last.state
  SalaryAdjustment Load (9.8ms)  SELECT  "salary_adjustments".* FROM "salary_adjustments" WHERE "salary_adjustments"."deleted_at" IS NULL  ORDER BY effective_date ASC LIMIT 1
 => nil
```

**Comment by seuros** [comment]
That a ActiveRecord Model , you need to use add the integration.

gem 'state_machines-activerecord'

**Comment by balancedcomp** [comment]
I'm an idiot - didn't see that. So do I need BOTH gems to get going?
state_machines and state_machines-activerecord or just the AR version?

On Thu, Sep 3, 2015 at 10:56 AM Abdelkader Boudih <notifications@github.com>
wrote:

> Closed #28 <https://github.com/state-machines/state_machines/issues/28>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/state-machines/state_machines/issues/28#event-400234530>
> .
>
-- 
Jarrett Green
CHIEF PRODUCT DEVELOPMENT OFFICER
_____________________________

tel.       316-927-2668
www.   balancedcomp.com
tw.       @balancedcomp

*BalancedComp*

*Calibrating Pay-to-Performance for Financial Institutions*

**Comment by seuros** [comment]
state_machines-activerecord will add the required gems.

**Comment by balancedcomp** [comment]
Thanks so much!

On Thu, Sep 3, 2015 at 11:14 AM Abdelkader Boudih <notifications@github.com>
wrote:

> state_machines-activerecord will add the required gems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/state-machines/state_machines/issues/28#issuecomment-137499226>
> .
>
-- 
Jarrett Green
CHIEF PRODUCT DEVELOPMENT OFFICER
_____________________________

tel.       316-927-2668
www.   balancedcomp.com
tw.       @balancedcomp

*BalancedComp*

*Calibrating Pay-to-Performance for Financial Institutions*
