### ISSUE TITLE
Doesn't seem to respect conditional validations

### ISSUE THREAD

**Issue by UnderpantsGnome** [state-machines/state_machines#30]
I have a model with a conditional validation

    validates :nda_accepted,
      presence: true,
      unless: :draft?

but if I try to transition it fails.

    >> Rfq.last.valid?
    => true
    >> Rfq.last.delete_draft!
    StateMachines::InvalidTransition: Cannot transition state via :delete_draft from :draft (Reason(s): Nda accepted can't be blank)
    from /Users/mmoen/code/UnderpantsGnome/britehub-app/vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/event.rb:224:in `block in add_actions'

**Comment by UnderpantsGnome** [comment]
So what does it take to get this working in a standard Rails 4 app? I have the following in my Gemfile and I still get the above results. 

    gem 'state_machines', '~> 0.4.0'
    gem 'state_machines-activerecord', '~> 0.3.0'
    gem 'state_machines-activemodel', '~> 0.3.0'

**Comment by seuros** [comment]
Just ```gem 'state_machines-activerecord'``` will depend on the other gems.

Could you open an issue in the state_machines-activerecord repo instead ?

**Comment by UnderpantsGnome** [comment]
Will do, sorry about that. I guess the coffee hasn't kicked in yet.
