### ISSUE TITLE
Pluginaweek attribution

### ISSUE THREAD

**Issue by espen** [state-machines/state_machines#38]
Thanks for bringing back life to this gem. state_machine was a major reason why we delayed upgrading to Rails 4.2 and with state_machines we have upgraded without any issues :)

The license and gemspec does include reference to the author of state_machine but I think it's fair that the original project https://github.com/pluginaweek/state_machine is attributed in the readme. Right now there is no way of telling that this project was originally forked from state_machine.

I can make a pull request but just wanted to open an issue for any input about this and also about the wording if the pull request is welcome. I think this pull request should also include some info about state_machines not only being a project that works with Rails 4 but also that it's a drop-in upgrade from state_machine. That's useful info for users who have found articles about state_machine but is unable to get it to work.

Again: thanks for your work. I'm sure there are many businesses depending on this gem, if the project is taking up a lot of your time I can suggest putting up some info on how businesses can help contribute to the development.

**Comment by rosskevin** [comment]
I would do two things:
1. PR here with a section towards the bottom addressing credit and:
  - mentioning an _almost_ dropin replacement
  - note that this project is agnostic of rails
  - rails support is added with child projects (add links to them)
2. PR at pluginaweek requesting updating their readme to point directly to your section.  This may or may not be accepted, but it's worth a shot and the audit trail guys had no problem doing it for that plugin.

**Comment by espen** [comment]
Ah yes, good suggestions, the state_machines-activerecord requirement should be made clearer for Rails usage and state_machine upgrade.

**Comment by seuros** [comment]
@espen 
https://github.com/state-machines/state_machines/blob/master/state_machines.gemspec#L8-L9
https://github.com/state-machines/state_machines/blob/master/Contributors.md

Feel free to add anything missing or necessary.

Thank you for your concern.

**Comment by mattvanhorn** [comment]
I think this would be very useful, as I spent a bit of time this morning trying to ascertain the relationship of this to the older gem.

**Comment by rosskevin** [comment]
@mattvanhorn PRs welcome

**Comment by hooptie45** [comment]
It's unfortunate we lost the history in the process. I'm wondering if we could integrate these changes into a fork of the original; within the state-machines org.

**Comment by betamatt** [comment]
Honestly, I'm incredibly uncomfortable touching this without the original history, both from an attribution and a technical perspective. There's no reason why the commit log had to be tossed out and there's a huge amount of knowledge lost in the process. 

I think it would be worth eating the full rebase in order to correct the history.

**Comment by seuros** [comment]
@betamatt Fell free to fork the other gem and spend sometime working on it to make yourself confortable. 

If you can provide a version like that, i think we might consider using it.

The gem was split into multiple smaller gems btw.

I'm closing this issue as nobody seem interested in doing the actual work.
