### ISSUE TITLE
dynamic + ActiveRecord

### ISSUE THREAD

**Issue by thiagoliof** [state-machines/state_machines#40]
Guys, im tryng implement one dynamic state machive, but i dont kown where i making mistake.
im following this approach https://github.com/state-machines/state_machines#static--dynamic-definitions
but the state dont saved in DB.
I can retrieve state on the fly only using by console, but if i close terminal session and open another 
session, the state always set :initial and DB Column is Nil
someone can help me?

im using Rails 4.2.4 and Ruby 2.1.1

**Comment by seuros** [comment]
You probably need to use state_machines-activerecord

**Comment by thiagoliof** [comment]
my gem file has 
gem 'state_machines-activerecord'

if i remove dymamic approach be ok, but if i use dymamic way  the data "initial" not persisted on database. i dont know where i making mistake

**Comment by seuros** [comment]
let open this issue in the other repo. 
could you provide a sample app ?

**Comment by thiagoliof** [comment]
Ok @seuros 
i reproduce the issue in below repo
https://github.com/thiagoliof/testFlow
tks for all
