### ISSUE TITLE
undefined local variable or method `state_paths'

### ISSUE THREAD

**Issue by daslicious** [state-machines/state_machines#41]
In the readme I saw that `state_paths` was a method defined on a model instance.  Does the readme need some cleanup or am I doing something wrong?

**Comment by SirRawlins** [comment]
@danhodge came your question while searching to see how `state_paths` is implemented in the codebase. I'm running the latest version `0.4.0` and can use the `state_paths` method without any issues.

Did you solve your problem?

**Comment by victornamuso** [comment]
Do you have a different column name for state? For instance I use status. So for me it's status_paths rather than state_paths.

**Comment by daslicious** [comment]
@victornamuso Thanks, I'll close this.

**Comment by victornamuso** [comment]
@daslicious Glad it worked. I'm going to read over the readme to see if possibly that could be made clearer.
