### ISSUE TITLE
Store state in a file?

### ISSUE THREAD

**Issue by logicminds** [state-machines/state_machines#64]
I want to use this in a CLI workflow based App.  I don't have any need for a database so I was hoping I can store the state in a file.  Does this gem allow me to store the state in a file?

And how would I do so?

**Comment by seuros** [comment]
Maybe have the getter and setter read/write to the file .

**Comment by logicminds** [comment]
getter and setter of what exactly.  Can you provide an example?  Should I be setting @state in the init method?

**Comment by rafaelfranca** [comment]
Get and setter of the state.

```ruby
class Foo
  state_machine :state do
     #...
  end

  def state
    File.read(some_path)
  end
  
  def state=(new_state)
    File.write(some_path, new_state)
  end
end
```
