### ISSUE TITLE
Localization / input collection

### ISSUE THREAD

**Issue by seliverstov-maxim** [state-machines/state_machines#70]
Hi. I try to use state_machines for my project. Could you please explain, are there collection_helpers for forms and an integration with I18n?

Thank you.

**Comment by seliverstov-maxim** [comment]
I gues some thing like this: `some_user.status_transitions.map { |e| [e.to, e.to_name }` for input_collection building

**Comment by rafaelfranca** [comment]
Thank you for the issue. There are no helpers for that. Neither integration with I18n. You will have to build yourself.
