### ISSUE TITLE
Find the required states for an event without an instance

### ISSUE THREAD

**Issue by Papipo** [state-machines/state_machines#72]
Hi!

How can I find which states can an event transition from without an instance of the underlying model?

I have this code working that uses the machine `states`, their `branches` and their `state_requirements` `values`, but it seems too involved and coupled to the library.

Thanks.

**Comment by seuros** [comment]
You will need the instance as a state machine can perform differently dependent on the instance linked to it .

**Comment by Papipo** [comment]
Even `state_machine` needs something like this: https://github.com/state-machines/state_machines/blob/master/lib/state_machines/event.rb#L194.

But we can close the issue anyway, I ended up doing something similar to the code above.

Thanks!
