### ISSUE TITLE
with_state approach 

### ISSUE THREAD

**Issue by pragmaticivan** [state-machines/state_machines#8]
Hi, I'm trying to migrate my app to use this gem now, I was using `with_state` of the last gem, did you guys have removed this?

ex:

```
Coupon.with_state(:active)
Coupon.with_states(:active, :completed)
```

**Comment by seuros** [comment]
Is Coupon a ActiveRecord model ?

**Comment by pragmaticivan** [comment]
Yes @seuros

**Comment by pragmaticivan** [comment]
If you check on the old gem, you can see on the `.methods` method that we can use the with_state and without_state approach.

**Comment by seuros** [comment]
That part of the activerecord integration : https://github.com/state-machines/state_machines-activerecord. 
This gem is the core only for POROs.

**Comment by pragmaticivan** [comment]
Thanks.
