### ISSUE TITLE
Ability to dynamically set state

### ISSUE THREAD

**Issue by dylan-hoefsloot** [state-machines/state_machines#89]
I would like to do something like this
```
class Project
  attr_accessor :field

  state_machine :state do
    event :dynamic do |project|
      transition to: project.calculate_statue
    end
  end

  def calculate_state
    case field do
    when "something"
      :rejected
    when "otherthing"
      :approved
    end
  end
end
```
where the state being transitioned to can be dynamically calculated via information that is stored on the class containing the state machine, similar to how the `do:` block works in `after_transition`.

Is this possible? or is this something that you would consider adding?

**Comment by seuros** [comment]
Possible, the example is on the readme
