### ISSUE TITLE
Question: after_transition do: []

### ISSUE THREAD

**Issue by rosskevin** [state-machines/state_machines#9]
Can I assume that most of the DSL will allow arrays i.e.

```ruby
after_transition on: :paid, do: [:process_payment, :notify_paid]
```

I don't see anything like that in the docs but [it appears to be acceptable in the code](https://github.com/state-machines/state_machines/blob/master/lib/state_machines/callback.rb#L129).

Also, the readme references `documentation`, other than code docs is there something else I can read to get a full understanding?  Is there a better place to ask questions?

And...thanks for taking this over.

**Comment by seuros** [comment]
Yes the DSL do allow arrays and block.

Right now the documentation is lacking but PRs are welcome. I don't have much free time to update it.
